<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Jai" name="BasicTest" tests="4" failures="1" timestamp="25 Nov 2015 06:13:44 GMT" time="0.021" errors="0">
  <testcase name="testAdd" time="0.007" classname="com.devfactory.testng.test.BasicSimpleTest"/>
  <testcase name="testPositiveHelloWorld" time="0.001" classname="com.devfactory.testng.test.TestHelloWorld"/>
  <testcase name="testPositiveHelloWorld" time="0.0" classname="com.devfactory.testng.test.TestExerciseIntro"/>
  <testcase name="testPositiveMethod2" time="0.001" classname="com.devfactory.testng.test.TestMethod2">
    <failure type="java.lang.AssertionError" message="Introduce Fail UT">
      <![CDATA[java.lang.AssertionError: Introduce Fail UT
	at com.devfactory.testng.test.TestMethod2.testPositiveMethod2(TestMethod2.java:27)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- testPositiveMethod2 -->
</testsuite> <!-- BasicTest -->
